### PR TITLE
Update to TEA framework 0.13

### PR DESCRIPTION
**Pull request by rudolf-adamkovic**

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
Build error. TEA runs SwiftLint during build but we don't use SwiftLint here. Investigating.

**Comment by rudolf-adamkovic** [comment]
Works now. Ready to be reviewed.

**Comment by andris-zalitis** [comment]
In review

**Review by andris-zalitis — APPROVED** [review]
Excellent work!

**Pull request merged**
