### PR TITLE
Rewrite to idiomatic Swift

### LINKED ISSUE #65: Update TEA to 0.15+

### LINKED ISSUE #77: Rewrite to idiomatic Swift

### PR DESCRIPTION
**Pull request by rudolf-adamkovic**
Close #77

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
Actually, let me cancel my review request here. Soon, we will have a new (state machine) framework in place and it would be a good idea to bump this to that one. Waiting.

**Comment by nasakinmaxim** [comment]
@salutis Could you please update it to the latest Stateful? Need this one done to start working on https://github.com/enfluid/emotion-code/issues/284.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim I'm on it.

**Comment by rudolf-adamkovic** [comment]
Work in progress.

**Comment by rudolf-adamkovic** [comment]
This is pretty much done. There may be bugs as I'm not able to test it with the Emotion Code app. The reason for that is that the app uses an ancient version of TEA/Stateful for chart layouts. Reassigning to @nasakinmaxim who's upgrading the chart layouts right now.

Max, be sure to test this throughly — with and without internet, all buttons, seeking towards the very end and beginning, remote control, lock screen, etc.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim 

Important:

1. The public API has changed. Before, we had just a single method — `prepareToLoad(URL?)`. Now we have two — `prepareToLoad(URL)` and `reset`. This is due to accidental limitations when using the newest version of Stateful. Anyway, be sure to update Emotion Code to call `prepareToLoad(URL)` and `reset` instead of just the former.
2. When the user tries to seek forward "past" the very end, we used to stop the player manually. Now, we just move the playhead and rely on the standard `.playerDidPlayToEnd` event. I'm not sure `AVPlayer` will do its job here. Please test throughly.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim I'm going to update this to the latest Stateful without `switch` statements now.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim After 2 hours, this is still WIP but we're almost there. I converted everything except tests for `ReadyToPlayState`. Have 2 calls now and will continue as soon as I can. Please take a look, I think it looks fantastic compared to everything we've tried before.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim Oh, also — I removed combined "play or pause" events. It would duplicate test code, so it's probably code smell. We will need to figure out how to plug it in.

**Comment by rudolf-adamkovic** [comment]
Updated:

* Updated Stateful framework with all required capabilities
* Updated Audio Bar core to the latest Stateful
* Re-added `prepareToLoad(URL?)`
* Re-added `userDidTapPlayPauseButton()`
* Removed temporary `reset` methods

Next up for @nasakinmaxim:

* Update `AudioBarViewController` to work with the new core
* Improve readability (= simplify) `ReadyToPlayState.present()`

**Comment by nasakinmaxim** [comment]
@salutis
Can't run unit tests, Xcode says `Build failed` without any additional info.
Also, can't import `AudioBarCore` in `AudioBarViewController`:
screenshot 2017-04-06 18 52 58

Before looking into the problem, I suggest cleaning `DerivedData` folder.

**Comment by nasakinmaxim** [comment]
@salutis
Stubs aren't working in `ReadyToPlayStateTests`.
screenshot 2017-04-12 12 34 45

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim Just wait for the final version of the framework.

**Comment by rudolf-adamkovic** [comment]
Updated title and description.

**Comment by rudolf-adamkovic** [comment]
Continues in #78.

**Pull request closed without merging**
