### PR TITLE
Update SwiftLint version checker

### PR DESCRIPTION
**Pull request by nasakinmaxim**

### CODE REVIEW

**Comment by nasakinmaxim** [comment]
BuddyBuild has an outdated version of SwiftLint. We have `buddybuild_postclone.sh` shell script, but CI upgrades only to `0.17.0`, when the latest version is `0.18.1`.
@salutis Any ideas?

PS: The PR is blocking https://github.com/enfluid/emotion-code/pull/364.

**Comment by rudolf-adamkovic** [comment]
Contacted BuddyBuild via the integrated chat:

> When running `brew upgrade swiftlint` from `buddybuild_postclone.sh`, it installs SwiftLint 0.17.0 instead of the latest is 0.18.1. Why is that?

Waiting for reply.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim Got reply from Buddy Build:

> Hi Rudolf -- You may need to run "brew update" at some point beforehand to update the list of formulae on the system.

**Comment by nasakinmaxim** [comment]
@salutis
Thanks! Going to update `buddybuild_postclone.sh`.

**Review by rudolf-adamkovic — APPROVED** [review]

**Pull request merged**
