### PR TITLE
Localize alert messages

### LINKED ISSUE #8: Localize alert message(s)
E.g.

```swift
.showAlert(text: "Unable to load media", button: "OK")
```

### PR DESCRIPTION
**Pull request by nasakinmaxim**
Close #8.

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim The trick is to figure out how to test localized strings. That's why I didn't add them right away. Needs research.

**Comment by nasakinmaxim** [comment]
@salutis Sure!
Keeping this PR for future implementation.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim 

> Keeping this PR for future implementation.

Future implementation you say? 😄 What's that?

**Comment by rudolf-adamkovic** [comment]
@andris-zalitis @ruslankmlv  Anybody knows how to test `NSLocalizedString` in a simple, elegant way? Folks, we need to figure this out.

**Comment by nasakinmaxim** [comment]
@salutis 
>Future implementation you say? 😄 What's that?

Sorry, that was a poor choice of words. 😅

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim Any progress on this one?

**Comment by nasakinmaxim** [comment]
@salutis
Still haven't found any clear way to test `NSLocalizedString`.
Should we merge the PR?

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim 

> Should we merge the PR?

No. The functional core is fully unit tested.

Closing for now. Once we know how, we can proceed.

**Pull request closed without merging**
