### PR TITLE
Allow to load "nil" URL

### PR DESCRIPTION
**Pull request by rudolf-adamkovic**

### CODE REVIEW

**Review by nasakinmaxim — CHANGES_REQUESTED** [review]
Unit tests are failing. Consider updating them.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim 

> Unit tests are failing. Consider updating them.

Not failing, they didn't compile. Oops! Fixed.

**Comment by nasakinmaxim** [comment]
In review.

**Review by nasakinmaxim — APPROVED** [review]
LGTM. Thanks!

**Comment by nasakinmaxim** [comment]
Waiting for CI.

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim Thank you!

**Pull request merged**
